apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-oauth2
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4180
    protocol: TCP
  selector:
    app: rethinkdb-oauth2